# torch 常用API

In [1]:
from pprint import pprint as p
import torch

In [27]:
x = torch.randn((1, 3, 4), dtype = torch.float32)
y = torch.zeros_like(x)
p(x)
p(y)

tensor([[[-0.2304,  1.6380,  0.7397,  0.3390],
         [-0.8128, -0.7826, -0.7577, -0.3546],
         [ 1.2946, -0.8645, -0.1968,  0.0474]]])
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


## torch.eye(x, y)

其中x是行，y是列

In [28]:
_ = torch.eye(3, dtype = torch.float32)
_local = torch.eye(4, 3)
p(_)
p(_local)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 0., 0.]])


## torch.unsqueeze(x: Tensor, dim: [int | tuple]), torch.squeeze(x: Tensor, dim: [int | tuple, optional] )

if dim given, the input will be squeezed only in the specified dimensions.

默认而言，squeeze是全部维度


In [35]:
p(torch.unsqueeze(x).shape)
p(torch.unsqueeze(x, dim = 2).shape)
p(torch.squeeze(x).shape)

TypeError: unsqueeze() missing 1 required positional arguments: "dim"

## torch.max(input: Tensor ,dim: int, keepdim: bool )

其中，dim表示要降低的维度，keepdim表示是否要降低维度

In [34]:
p(x.shape)
p(torch.max(x, 2))
p("===========")
p(torch.max(x, 2, keepdim = True))

torch.Size([1, 3, 4])
torch.return_types.max(
values=tensor([[ 1.6380, -0.3546,  1.2946]]),
indices=tensor([[1, 3, 0]]))
'==========='
torch.return_types.max(
values=tensor([[[ 1.6380],
         [-0.3546],
         [ 1.2946]]]),
indices=tensor([[[1],
         [3],
         [0]]]))
